--name=cdr-2-upwind-sparse0-noise0.001-id0 --kernel_size=5 --viscosity=0.1 --blocks=0,0,0-6,9 --dataname=cdr --constraint=2 --device=cuda:0 --stablize=0 --sparsity=0 --momentsparsity=0.001 --data_start_time=1 --dt=1e-2 --max_dt=1e-4 --hidden_layers=5 --start_noise=0.001 --end_noise=0.001 --scheme=upwind
0
--name=cdr-2-upwind-sparse0-noise0.001-id1 --kernel_size=5 --viscosity=0.1 --blocks=0,0,0-6,9 --dataname=cdr --constraint=2 --device=cuda:1 --stablize=0 --sparsity=0 --momentsparsity=0.001 --data_start_time=1 --dt=1e-2 --max_dt=1e-4 --hidden_layers=5 --start_noise=0.001 --end_noise=0.001 --scheme=upwind
1
--name=cdr-2-upwind-sparse0-noise0.001-id2 --kernel_size=5 --viscosity=0.1 --blocks=0,0,0-6,9 --dataname=cdr --constraint=2 --device=cuda:2 --stablize=0 --sparsity=0 --momentsparsity=0.001 --data_start_time=1 --dt=1e-2 --max_dt=1e-4 --hidden_layers=5 --start_noise=0.001 --end_noise=0.001 --scheme=upwind
2
--name=cdr-2-upwind-sparse0-noise0.001-id3 --kernel_size=5 --viscosity=0.1 --blocks=0,0,0-6,9 --dataname=cdr --constraint=2 --device=cuda:3 --stablize=0 --sparsity=0 --momentsparsity=0.001 --data_start_time=1 --dt=1e-2 --max_dt=1e-4 --hidden_layers=5 --start_noise=0.001 --end_noise=0.001 --scheme=upwind
3
wait
{'--name': 'cdr-2-upwind-sparse0-noise0.001-id3', '--dtype': 'double', '--device': 'cuda:3', '--constraint': '2', '--dt': 0.01, '--cell_num': 1, '--eps': 6.283185307179586, '--blocks': [0, 0, 0, 1, 2, 3, 4, 5, 6, 9], '--kernel_size': 5, '--max_order': 2, '--dx': 0.19634954084936207, '--hidden_layers': 5, '--scheme': 'upwind', '--dataname': 'cdr', '--viscosity': 0.1, '--zoom': 4, '--max_dt': 0.0001, '--batch_size': 28, '--data_timescheme': 'rk2', '--channel_names': 'u,v', '--freq': 4, '--data_start_time': 1.0, '--start_noise': 0.001, '--end_noise': 0.001, '--stablize': 0.0, '--sparsity': 0.0, '--momentsparsity': 0.001, '--npseed': -1, '--torchseed': -1, '--maxiter': 2000, '--recordfile': 'None', '--recordcycle': 200, '--savecycle': -1, '--start_from': -1}
Traceback (most recent call last):
  File "train.py", line 58, in <module>
    globalnames, callback, model, data_model, sampling, addnoise = setenv.setenv(options)
  File "/data/users2/sajad/code/PDE-Net/setenv.py", line 68, in setenv
    globalnames, callback, model = _set_model(options)
  File "/data/users2/sajad/code/PDE-Net/setenv.py", line 45, in _set_model
    model.to(globalnames['device'])
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 386, in to
    return self._apply(convert)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 205, in _apply
    self._buffers[key] = fn(buf)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 384, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
{'--name': 'cdr-2-upwind-sparse0-noise0.001-id1', '--dtype': 'double', '--device': 'cuda:1', '--constraint': '2', '--dt': 0.01, '--cell_num': 1, '--eps': 6.283185307179586, '--blocks': [0, 0, 0, 1, 2, 3, 4, 5, 6, 9], '--kernel_size': 5, '--max_order': 2, '--dx': 0.19634954084936207, '--hidden_layers': 5, '--scheme': 'upwind', '--dataname': 'cdr', '--viscosity': 0.1, '--zoom': 4, '--max_dt': 0.0001, '--batch_size': 28, '--data_timescheme': 'rk2', '--channel_names': 'u,v', '--freq': 4, '--data_start_time': 1.0, '--start_noise': 0.001, '--end_noise': 0.001, '--stablize': 0.0, '--sparsity': 0.0, '--momentsparsity': 0.001, '--npseed': -1, '--torchseed': -1, '--maxiter': 2000, '--recordfile': 'None', '--recordcycle': 200, '--savecycle': -1, '--start_from': -1}
block:  0
name:  cdr-2-upwind-sparse0-noise0.001-id1
device:  cuda:1
generate a random number to check random seed:  0.5929698905327596
current stage is: warmup
u_obs shape: batchsize x channelNum x xgridsize x ygridsize
torch.Size([28, 2, 32, 32])
u_obs.abs().max()
tensor(3.7659, device='cuda:1', dtype=torch.float64)
u_obs variance
tensor([1.0117, 0.0869, 0.1155, 0.0989, 0.0968, 0.0928, 0.5252, 0.0988, 0.1263,
        0.0000, 0.0000, 0.0000], device='cuda:1', dtype=torch.float64,
       grad_fn=<MeanBackward2>)
cublas runtime error : the GPU program failed to execute at /tmp/pip-req-build-hv8qeyyw/aten/src/THC/THCBlas.cu:348
Traceback (most recent call last):
  File "train.py", line 159, in <module>
    nfi.flat_param = xopt
NameError: name 'xopt' is not defined
{'--name': 'cdr-2-upwind-sparse0-noise0.001-id2', '--dtype': 'double', '--device': 'cuda:2', '--constraint': '2', '--dt': 0.01, '--cell_num': 1, '--eps': 6.283185307179586, '--blocks': [0, 0, 0, 1, 2, 3, 4, 5, 6, 9], '--kernel_size': 5, '--max_order': 2, '--dx': 0.19634954084936207, '--hidden_layers': 5, '--scheme': 'upwind', '--dataname': 'cdr', '--viscosity': 0.1, '--zoom': 4, '--max_dt': 0.0001, '--batch_size': 28, '--data_timescheme': 'rk2', '--channel_names': 'u,v', '--freq': 4, '--data_start_time': 1.0, '--start_noise': 0.001, '--end_noise': 0.001, '--stablize': 0.0, '--sparsity': 0.0, '--momentsparsity': 0.001, '--npseed': -1, '--torchseed': -1, '--maxiter': 2000, '--recordfile': 'None', '--recordcycle': 200, '--savecycle': -1, '--start_from': -1}
block:  0
name:  cdr-2-upwind-sparse0-noise0.001-id2
device:  cuda:2
generate a random number to check random seed:  0.014562433305215672
current stage is: warmup
u_obs shape: batchsize x channelNum x xgridsize x ygridsize
torch.Size([28, 2, 32, 32])
u_obs.abs().max()
tensor(3.8306, device='cuda:2', dtype=torch.float64)
u_obs variance
tensor([0.9950, 0.0943, 0.1020, 0.0950, 0.1011, 0.1050, 0.5886, 0.0906, 0.1079,
        0.0000, 0.0000, 0.0000], device='cuda:2', dtype=torch.float64,
       grad_fn=<MeanBackward2>)
cublas runtime error : the GPU program failed to execute at /tmp/pip-req-build-hv8qeyyw/aten/src/THC/THCBlas.cu:348
Traceback (most recent call last):
  File "train.py", line 159, in <module>
    nfi.flat_param = xopt
NameError: name 'xopt' is not defined
{'--name': 'cdr-2-upwind-sparse0-noise0.001-id0', '--dtype': 'double', '--device': 'cuda:0', '--constraint': '2', '--dt': 0.01, '--cell_num': 1, '--eps': 6.283185307179586, '--blocks': [0, 0, 0, 1, 2, 3, 4, 5, 6, 9], '--kernel_size': 5, '--max_order': 2, '--dx': 0.19634954084936207, '--hidden_layers': 5, '--scheme': 'upwind', '--dataname': 'cdr', '--viscosity': 0.1, '--zoom': 4, '--max_dt': 0.0001, '--batch_size': 28, '--data_timescheme': 'rk2', '--channel_names': 'u,v', '--freq': 4, '--data_start_time': 1.0, '--start_noise': 0.001, '--end_noise': 0.001, '--stablize': 0.0, '--sparsity': 0.0, '--momentsparsity': 0.001, '--npseed': -1, '--torchseed': -1, '--maxiter': 2000, '--recordfile': 'None', '--recordcycle': 200, '--savecycle': -1, '--start_from': -1}
block:  0
name:  cdr-2-upwind-sparse0-noise0.001-id0
device:  cuda:0
generate a random number to check random seed:  -0.4326387775912188
current stage is: warmup
u_obs shape: batchsize x channelNum x xgridsize x ygridsize
torch.Size([28, 2, 32, 32])
u_obs.abs().max()
tensor(3.9084, device='cuda:0', dtype=torch.float64)
u_obs variance
tensor([1.0056, 0.0806, 0.0980, 0.0907, 0.0866, 0.0783, 0.5319, 0.0842, 0.1016,
        0.0000, 0.0000, 0.0000], device='cuda:0', dtype=torch.float64,
       grad_fn=<MeanBackward2>)
cublas runtime error : the GPU program failed to execute at /tmp/pip-req-build-hv8qeyyw/aten/src/THC/THCBlas.cu:348
Traceback (most recent call last):
  File "train.py", line 159, in <module>
    nfi.flat_param = xopt
NameError: name 'xopt' is not defined
--name=cdr-2-upwind-sparse0-noise0.001-id4 --kernel_size=5 --viscosity=0.1 --blocks=0,0,0-6,9 --dataname=cdr --constraint=2 --device=cuda:0 --stablize=0 --sparsity=0 --momentsparsity=0.001 --data_start_time=1 --dt=1e-2 --max_dt=1e-4 --hidden_layers=5 --start_noise=0.001 --end_noise=0.001 --scheme=upwind
0
--name=cdr-2-upwind-sparse0-noise0.001-id5 --kernel_size=5 --viscosity=0.1 --blocks=0,0,0-6,9 --dataname=cdr --constraint=2 --device=cuda:1 --stablize=0 --sparsity=0 --momentsparsity=0.001 --data_start_time=1 --dt=1e-2 --max_dt=1e-4 --hidden_layers=5 --start_noise=0.001 --end_noise=0.001 --scheme=upwind
1
--name=cdr-2-upwind-sparse0-noise0.001-id6 --kernel_size=5 --viscosity=0.1 --blocks=0,0,0-6,9 --dataname=cdr --constraint=2 --device=cuda:2 --stablize=0 --sparsity=0 --momentsparsity=0.001 --data_start_time=1 --dt=1e-2 --max_dt=1e-4 --hidden_layers=5 --start_noise=0.001 --end_noise=0.001 --scheme=upwind
2
--name=cdr-2-upwind-sparse0-noise0.001-id7 --kernel_size=5 --viscosity=0.1 --blocks=0,0,0-6,9 --dataname=cdr --constraint=2 --device=cuda:3 --stablize=0 --sparsity=0 --momentsparsity=0.001 --data_start_time=1 --dt=1e-2 --max_dt=1e-4 --hidden_layers=5 --start_noise=0.001 --end_noise=0.001 --scheme=upwind
3
wait
{'--name': 'cdr-2-upwind-sparse0-noise0.001-id7', '--dtype': 'double', '--device': 'cuda:3', '--constraint': '2', '--dt': 0.01, '--cell_num': 1, '--eps': 6.283185307179586, '--blocks': [0, 0, 0, 1, 2, 3, 4, 5, 6, 9], '--kernel_size': 5, '--max_order': 2, '--dx': 0.19634954084936207, '--hidden_layers': 5, '--scheme': 'upwind', '--dataname': 'cdr', '--viscosity': 0.1, '--zoom': 4, '--max_dt': 0.0001, '--batch_size': 28, '--data_timescheme': 'rk2', '--channel_names': 'u,v', '--freq': 4, '--data_start_time': 1.0, '--start_noise': 0.001, '--end_noise': 0.001, '--stablize': 0.0, '--sparsity': 0.0, '--momentsparsity': 0.001, '--npseed': -1, '--torchseed': -1, '--maxiter': 2000, '--recordfile': 'None', '--recordcycle': 200, '--savecycle': -1, '--start_from': -1}
Traceback (most recent call last):
  File "train.py", line 58, in <module>
    globalnames, callback, model, data_model, sampling, addnoise = setenv.setenv(options)
  File "/data/users2/sajad/code/PDE-Net/setenv.py", line 68, in setenv
    globalnames, callback, model = _set_model(options)
  File "/data/users2/sajad/code/PDE-Net/setenv.py", line 45, in _set_model
    model.to(globalnames['device'])
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 386, in to
    return self._apply(convert)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 205, in _apply
    self._buffers[key] = fn(buf)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 384, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
{'--name': 'cdr-2-upwind-sparse0-noise0.001-id4', '--dtype': 'double', '--device': 'cuda:0', '--constraint': '2', '--dt': 0.01, '--cell_num': 1, '--eps': 6.283185307179586, '--blocks': [0, 0, 0, 1, 2, 3, 4, 5, 6, 9], '--kernel_size': 5, '--max_order': 2, '--dx': 0.19634954084936207, '--hidden_layers': 5, '--scheme': 'upwind', '--dataname': 'cdr', '--viscosity': 0.1, '--zoom': 4, '--max_dt': 0.0001, '--batch_size': 28, '--data_timescheme': 'rk2', '--channel_names': 'u,v', '--freq': 4, '--data_start_time': 1.0, '--start_noise': 0.001, '--end_noise': 0.001, '--stablize': 0.0, '--sparsity': 0.0, '--momentsparsity': 0.001, '--npseed': -1, '--torchseed': -1, '--maxiter': 2000, '--recordfile': 'None', '--recordcycle': 200, '--savecycle': -1, '--start_from': -1}
block:  0
name:  cdr-2-upwind-sparse0-noise0.001-id4
device:  cuda:0
generate a random number to check random seed:  0.23489510253454027
current stage is: warmup
u_obs shape: batchsize x channelNum x xgridsize x ygridsize
torch.Size([28, 2, 32, 32])
u_obs.abs().max()
tensor(3.8079, device='cuda:0', dtype=torch.float64)
u_obs variance
tensor([0.9935, 0.0880, 0.0781, 0.0838, 0.0831, 0.0965, 0.3833, 0.1018, 0.0837,
        0.0000, 0.0000, 0.0000], device='cuda:0', dtype=torch.float64,
       grad_fn=<MeanBackward2>)
cublas runtime error : the GPU program failed to execute at /tmp/pip-req-build-hv8qeyyw/aten/src/THC/THCBlas.cu:348
Traceback (most recent call last):
  File "train.py", line 159, in <module>
    nfi.flat_param = xopt
NameError: name 'xopt' is not defined
{'--name': 'cdr-2-upwind-sparse0-noise0.001-id6', '--dtype': 'double', '--device': 'cuda:2', '--constraint': '2', '--dt': 0.01, '--cell_num': 1, '--eps': 6.283185307179586, '--blocks': [0, 0, 0, 1, 2, 3, 4, 5, 6, 9], '--kernel_size': 5, '--max_order': 2, '--dx': 0.19634954084936207, '--hidden_layers': 5, '--scheme': 'upwind', '--dataname': 'cdr', '--viscosity': 0.1, '--zoom': 4, '--max_dt': 0.0001, '--batch_size': 28, '--data_timescheme': 'rk2', '--channel_names': 'u,v', '--freq': 4, '--data_start_time': 1.0, '--start_noise': 0.001, '--end_noise': 0.001, '--stablize': 0.0, '--sparsity': 0.0, '--momentsparsity': 0.001, '--npseed': -1, '--torchseed': -1, '--maxiter': 2000, '--recordfile': 'None', '--recordcycle': 200, '--savecycle': -1, '--start_from': -1}
block:  0
name:  cdr-2-upwind-sparse0-noise0.001-id6
device:  cuda:2
generate a random number to check random seed:  0.3847784212842934
current stage is: warmup
u_obs shape: batchsize x channelNum x xgridsize x ygridsize
torch.Size([28, 2, 32, 32])
u_obs.abs().max()
tensor(3.6454, device='cuda:2', dtype=torch.float64)
u_obs variance
tensor([1.0005, 0.0973, 0.0940, 0.0844, 0.0810, 0.0987, 0.3418, 0.0799, 0.0899,
        0.0000, 0.0000, 0.0000], device='cuda:2', dtype=torch.float64,
       grad_fn=<MeanBackward2>)
cublas runtime error : the GPU program failed to execute at /tmp/pip-req-build-hv8qeyyw/aten/src/THC/THCBlas.cu:348
Traceback (most recent call last):
  File "train.py", line 159, in <module>
    nfi.flat_param = xopt
NameError: name 'xopt' is not defined
{'--name': 'cdr-2-upwind-sparse0-noise0.001-id5', '--dtype': 'double', '--device': 'cuda:1', '--constraint': '2', '--dt': 0.01, '--cell_num': 1, '--eps': 6.283185307179586, '--blocks': [0, 0, 0, 1, 2, 3, 4, 5, 6, 9], '--kernel_size': 5, '--max_order': 2, '--dx': 0.19634954084936207, '--hidden_layers': 5, '--scheme': 'upwind', '--dataname': 'cdr', '--viscosity': 0.1, '--zoom': 4, '--max_dt': 0.0001, '--batch_size': 28, '--data_timescheme': 'rk2', '--channel_names': 'u,v', '--freq': 4, '--data_start_time': 1.0, '--start_noise': 0.001, '--end_noise': 0.001, '--stablize': 0.0, '--sparsity': 0.0, '--momentsparsity': 0.001, '--npseed': -1, '--torchseed': -1, '--maxiter': 2000, '--recordfile': 'None', '--recordcycle': 200, '--savecycle': -1, '--start_from': -1}
block:  0
name:  cdr-2-upwind-sparse0-noise0.001-id5
device:  cuda:1
generate a random number to check random seed:  3.5009443475405377
current stage is: warmup
u_obs shape: batchsize x channelNum x xgridsize x ygridsize
torch.Size([28, 2, 32, 32])
u_obs.abs().max()
tensor(3.8780, device='cuda:1', dtype=torch.float64)
u_obs variance
tensor([0.9961, 0.1066, 0.1060, 0.1000, 0.0799, 0.0967, 0.5435, 0.0760, 0.0997,
        0.0000, 0.0000, 0.0000], device='cuda:1', dtype=torch.float64,
       grad_fn=<MeanBackward2>)
cublas runtime error : the GPU program failed to execute at /tmp/pip-req-build-hv8qeyyw/aten/src/THC/THCBlas.cu:348
Traceback (most recent call last):
  File "train.py", line 159, in <module>
    nfi.flat_param = xopt
NameError: name 'xopt' is not defined
--name=cdr-2-upwind-sparse0-noise0.001-id8 --kernel_size=5 --viscosity=0.1 --blocks=0,0,0-6,9 --dataname=cdr --constraint=2 --device=cuda:0 --stablize=0 --sparsity=0 --momentsparsity=0.001 --data_start_time=1 --dt=1e-2 --max_dt=1e-4 --hidden_layers=5 --start_noise=0.001 --end_noise=0.001 --scheme=upwind
0
--name=cdr-2-upwind-sparse0-noise0.001-id9 --kernel_size=5 --viscosity=0.1 --blocks=0,0,0-6,9 --dataname=cdr --constraint=2 --device=cuda:1 --stablize=0 --sparsity=0 --momentsparsity=0.001 --data_start_time=1 --dt=1e-2 --max_dt=1e-4 --hidden_layers=5 --start_noise=0.001 --end_noise=0.001 --scheme=upwind
1
--name=cdr-2-upwind-sparse0-noise0.001-id10 --kernel_size=5 --viscosity=0.1 --blocks=0,0,0-6,9 --dataname=cdr --constraint=2 --device=cuda:2 --stablize=0 --sparsity=0 --momentsparsity=0.001 --data_start_time=1 --dt=1e-2 --max_dt=1e-4 --hidden_layers=5 --start_noise=0.001 --end_noise=0.001 --scheme=upwind
2
--name=cdr-2-upwind-sparse0-noise0.001-id11 --kernel_size=5 --viscosity=0.1 --blocks=0,0,0-6,9 --dataname=cdr --constraint=2 --device=cuda:3 --stablize=0 --sparsity=0 --momentsparsity=0.001 --data_start_time=1 --dt=1e-2 --max_dt=1e-4 --hidden_layers=5 --start_noise=0.001 --end_noise=0.001 --scheme=upwind
3
wait
{'--name': 'cdr-2-upwind-sparse0-noise0.001-id11', '--dtype': 'double', '--device': 'cuda:3', '--constraint': '2', '--dt': 0.01, '--cell_num': 1, '--eps': 6.283185307179586, '--blocks': [0, 0, 0, 1, 2, 3, 4, 5, 6, 9], '--kernel_size': 5, '--max_order': 2, '--dx': 0.19634954084936207, '--hidden_layers': 5, '--scheme': 'upwind', '--dataname': 'cdr', '--viscosity': 0.1, '--zoom': 4, '--max_dt': 0.0001, '--batch_size': 28, '--data_timescheme': 'rk2', '--channel_names': 'u,v', '--freq': 4, '--data_start_time': 1.0, '--start_noise': 0.001, '--end_noise': 0.001, '--stablize': 0.0, '--sparsity': 0.0, '--momentsparsity': 0.001, '--npseed': -1, '--torchseed': -1, '--maxiter': 2000, '--recordfile': 'None', '--recordcycle': 200, '--savecycle': -1, '--start_from': -1}
Traceback (most recent call last):
  File "train.py", line 58, in <module>
    globalnames, callback, model, data_model, sampling, addnoise = setenv.setenv(options)
  File "/data/users2/sajad/code/PDE-Net/setenv.py", line 68, in setenv
    globalnames, callback, model = _set_model(options)
  File "/data/users2/sajad/code/PDE-Net/setenv.py", line 45, in _set_model
    model.to(globalnames['device'])
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 386, in to
    return self._apply(convert)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 205, in _apply
    self._buffers[key] = fn(buf)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 384, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
{'--name': 'cdr-2-upwind-sparse0-noise0.001-id10', '--dtype': 'double', '--device': 'cuda:2', '--constraint': '2', '--dt': 0.01, '--cell_num': 1, '--eps': 6.283185307179586, '--blocks': [0, 0, 0, 1, 2, 3, 4, 5, 6, 9], '--kernel_size': 5, '--max_order': 2, '--dx': 0.19634954084936207, '--hidden_layers': 5, '--scheme': 'upwind', '--dataname': 'cdr', '--viscosity': 0.1, '--zoom': 4, '--max_dt': 0.0001, '--batch_size': 28, '--data_timescheme': 'rk2', '--channel_names': 'u,v', '--freq': 4, '--data_start_time': 1.0, '--start_noise': 0.001, '--end_noise': 0.001, '--stablize': 0.0, '--sparsity': 0.0, '--momentsparsity': 0.001, '--npseed': -1, '--torchseed': -1, '--maxiter': 2000, '--recordfile': 'None', '--recordcycle': 200, '--savecycle': -1, '--start_from': -1}
block:  0
name:  cdr-2-upwind-sparse0-noise0.001-id10
device:  cuda:2
generate a random number to check random seed:  -0.0777309804982885
current stage is: warmup
u_obs shape: batchsize x channelNum x xgridsize x ygridsize
torch.Size([28, 2, 32, 32])
u_obs.abs().max()
tensor(3.7881, device='cuda:2', dtype=torch.float64)
u_obs variance
tensor([1.0055, 0.1040, 0.0891, 0.0752, 0.0759, 0.0739, 0.4928, 0.0760, 0.0985,
        0.0000, 0.0000, 0.0000], device='cuda:2', dtype=torch.float64,
       grad_fn=<MeanBackward2>)
cublas runtime error : the GPU program failed to execute at /tmp/pip-req-build-hv8qeyyw/aten/src/THC/THCBlas.cu:348
Traceback (most recent call last):
  File "train.py", line 159, in <module>
    nfi.flat_param = xopt
NameError: name 'xopt' is not defined
{'--name': 'cdr-2-upwind-sparse0-noise0.001-id9', '--dtype': 'double', '--device': 'cuda:1', '--constraint': '2', '--dt': 0.01, '--cell_num': 1, '--eps': 6.283185307179586, '--blocks': [0, 0, 0, 1, 2, 3, 4, 5, 6, 9], '--kernel_size': 5, '--max_order': 2, '--dx': 0.19634954084936207, '--hidden_layers': 5, '--scheme': 'upwind', '--dataname': 'cdr', '--viscosity': 0.1, '--zoom': 4, '--max_dt': 0.0001, '--batch_size': 28, '--data_timescheme': 'rk2', '--channel_names': 'u,v', '--freq': 4, '--data_start_time': 1.0, '--start_noise': 0.001, '--end_noise': 0.001, '--stablize': 0.0, '--sparsity': 0.0, '--momentsparsity': 0.001, '--npseed': -1, '--torchseed': -1, '--maxiter': 2000, '--recordfile': 'None', '--recordcycle': 200, '--savecycle': -1, '--start_from': -1}
block:  0
name:  cdr-2-upwind-sparse0-noise0.001-id9
device:  cuda:1
generate a random number to check random seed:  1.558958244164718
current stage is: warmup
u_obs shape: batchsize x channelNum x xgridsize x ygridsize
torch.Size([28, 2, 32, 32])
u_obs.abs().max()
tensor(3.6312, device='cuda:1', dtype=torch.float64)
u_obs variance
tensor([1.0116, 0.0796, 0.1060, 0.0923, 0.0883, 0.0899, 0.3605, 0.0873, 0.1021,
        0.0000, 0.0000, 0.0000], device='cuda:1', dtype=torch.float64,
       grad_fn=<MeanBackward2>)
cublas runtime error : the GPU program failed to execute at /tmp/pip-req-build-hv8qeyyw/aten/src/THC/THCBlas.cu:348
Traceback (most recent call last):
  File "train.py", line 159, in <module>
    nfi.flat_param = xopt
NameError: name 'xopt' is not defined
{'--name': 'cdr-2-upwind-sparse0-noise0.001-id8', '--dtype': 'double', '--device': 'cuda:0', '--constraint': '2', '--dt': 0.01, '--cell_num': 1, '--eps': 6.283185307179586, '--blocks': [0, 0, 0, 1, 2, 3, 4, 5, 6, 9], '--kernel_size': 5, '--max_order': 2, '--dx': 0.19634954084936207, '--hidden_layers': 5, '--scheme': 'upwind', '--dataname': 'cdr', '--viscosity': 0.1, '--zoom': 4, '--max_dt': 0.0001, '--batch_size': 28, '--data_timescheme': 'rk2', '--channel_names': 'u,v', '--freq': 4, '--data_start_time': 1.0, '--start_noise': 0.001, '--end_noise': 0.001, '--stablize': 0.0, '--sparsity': 0.0, '--momentsparsity': 0.001, '--npseed': -1, '--torchseed': -1, '--maxiter': 2000, '--recordfile': 'None', '--recordcycle': 200, '--savecycle': -1, '--start_from': -1}
block:  0
name:  cdr-2-upwind-sparse0-noise0.001-id8
device:  cuda:0
generate a random number to check random seed:  0.46859366066606023
current stage is: warmup
u_obs shape: batchsize x channelNum x xgridsize x ygridsize
torch.Size([28, 2, 32, 32])
u_obs.abs().max()
tensor(3.9233, device='cuda:0', dtype=torch.float64)
u_obs variance
tensor([0.9954, 0.0841, 0.0754, 0.0774, 0.0865, 0.0885, 0.3884, 0.0958, 0.0976,
        0.0000, 0.0000, 0.0000], device='cuda:0', dtype=torch.float64,
       grad_fn=<MeanBackward2>)
cublas runtime error : the GPU program failed to execute at /tmp/pip-req-build-hv8qeyyw/aten/src/THC/THCBlas.cu:348
Traceback (most recent call last):
  File "train.py", line 159, in <module>
    nfi.flat_param = xopt
NameError: name 'xopt' is not defined
--name=cdr-2-upwind-sparse0-noise0.001-id12 --kernel_size=5 --viscosity=0.1 --blocks=0,0,0-6,9 --dataname=cdr --constraint=2 --device=cuda:0 --stablize=0 --sparsity=0 --momentsparsity=0.001 --data_start_time=1 --dt=1e-2 --max_dt=1e-4 --hidden_layers=5 --start_noise=0.001 --end_noise=0.001 --scheme=upwind
0
--name=cdr-2-upwind-sparse0-noise0.001-id13 --kernel_size=5 --viscosity=0.1 --blocks=0,0,0-6,9 --dataname=cdr --constraint=2 --device=cuda:1 --stablize=0 --sparsity=0 --momentsparsity=0.001 --data_start_time=1 --dt=1e-2 --max_dt=1e-4 --hidden_layers=5 --start_noise=0.001 --end_noise=0.001 --scheme=upwind
1
--name=cdr-2-upwind-sparse0-noise0.001-id14 --kernel_size=5 --viscosity=0.1 --blocks=0,0,0-6,9 --dataname=cdr --constraint=2 --device=cuda:2 --stablize=0 --sparsity=0 --momentsparsity=0.001 --data_start_time=1 --dt=1e-2 --max_dt=1e-4 --hidden_layers=5 --start_noise=0.001 --end_noise=0.001 --scheme=upwind
2
--name=cdr-2-upwind-sparse0-noise0.001-id15 --kernel_size=5 --viscosity=0.1 --blocks=0,0,0-6,9 --dataname=cdr --constraint=2 --device=cuda:3 --stablize=0 --sparsity=0 --momentsparsity=0.001 --data_start_time=1 --dt=1e-2 --max_dt=1e-4 --hidden_layers=5 --start_noise=0.001 --end_noise=0.001 --scheme=upwind
3
wait
slurmstepd: error: *** JOB 2769876 ON trendsdgxa001.rs.gsu.edu CANCELLED AT 2021-04-19T17:24:25 DUE TO PREEMPTION ***
