repeat batch:0, select device:0
NPSEED: 10, TORCHSEED: 100
repeat batch:1, select device:1
NPSEED: 20, TORCHSEED: 200
repeat batch:2, select device:2
NPSEED: 30, TORCHSEED: 300
repeat batch:3, select device:3
NPSEED: 40, TORCHSEED: 400
wait
configfile:  checkpoint/burgers-noise0.001/options.yaml
Traceback (most recent call last):
  File "_test_data_gen.py", line 21, in <module>
    globalnames, _, model, data_model, sampling, addnoise = setenv.setenv(options)
  File "/data/users2/sajad/code/PDE-Net/setenv.py", line 68, in setenv
    globalnames, callback, model = _set_model(options)
  File "/data/users2/sajad/code/PDE-Net/setenv.py", line 45, in _set_model
    model.to(globalnames['device'])
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 386, in to
    return self._apply(convert)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 205, in _apply
    self._buffers[key] = fn(buf)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 384, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
configfile:  checkpoint/burgers-noise0.001/options.yaml
configfile:  checkpoint/burgers-noise0.001/options.yaml
configfile:  checkpoint/burgers-noise0.001/options.yaml
repeat batch:4, select device:0
NPSEED: 50, TORCHSEED: 500
repeat batch:5, select device:1
NPSEED: 60, TORCHSEED: 600
repeat batch:6, select device:2
NPSEED: 70, TORCHSEED: 700
repeat batch:7, select device:3
NPSEED: 80, TORCHSEED: 800
wait
configfile:  checkpoint/burgers-noise0.001/options.yaml
Traceback (most recent call last):
  File "_test_data_gen.py", line 21, in <module>
    globalnames, _, model, data_model, sampling, addnoise = setenv.setenv(options)
  File "/data/users2/sajad/code/PDE-Net/setenv.py", line 68, in setenv
    globalnames, callback, model = _set_model(options)
  File "/data/users2/sajad/code/PDE-Net/setenv.py", line 45, in _set_model
    model.to(globalnames['device'])
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 386, in to
    return self._apply(convert)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 205, in _apply
    self._buffers[key] = fn(buf)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 384, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
configfile:  checkpoint/burgers-noise0.001/options.yaml
configfile:  checkpoint/burgers-noise0.001/options.yaml
configfile:  checkpoint/burgers-noise0.001/options.yaml
repeat batch:8, select device:0
NPSEED: 90, TORCHSEED: 900
repeat batch:9, select device:1
NPSEED: 100, TORCHSEED: 1000
repeat batch:10, select device:2
NPSEED: 110, TORCHSEED: 1100
repeat batch:11, select device:3
NPSEED: 120, TORCHSEED: 1200
wait
configfile:  checkpoint/burgers-noise0.001/options.yaml
Traceback (most recent call last):
  File "_test_data_gen.py", line 21, in <module>
    globalnames, _, model, data_model, sampling, addnoise = setenv.setenv(options)
  File "/data/users2/sajad/code/PDE-Net/setenv.py", line 68, in setenv
    globalnames, callback, model = _set_model(options)
  File "/data/users2/sajad/code/PDE-Net/setenv.py", line 45, in _set_model
    model.to(globalnames['device'])
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 386, in to
    return self._apply(convert)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 205, in _apply
    self._buffers[key] = fn(buf)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 384, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
configfile:  checkpoint/burgers-noise0.001/options.yaml
configfile:  checkpoint/burgers-noise0.001/options.yaml
configfile:  checkpoint/burgers-noise0.001/options.yaml
repeat batch:12, select device:0
NPSEED: 130, TORCHSEED: 1300
repeat batch:13, select device:1
NPSEED: 140, TORCHSEED: 1400
repeat batch:14, select device:2
NPSEED: 150, TORCHSEED: 1500
repeat batch:15, select device:3
NPSEED: 160, TORCHSEED: 1600
wait
configfile:  checkpoint/burgers-noise0.001/options.yaml
Traceback (most recent call last):
  File "_test_data_gen.py", line 21, in <module>
    globalnames, _, model, data_model, sampling, addnoise = setenv.setenv(options)
  File "/data/users2/sajad/code/PDE-Net/setenv.py", line 68, in setenv
    globalnames, callback, model = _set_model(options)
  File "/data/users2/sajad/code/PDE-Net/setenv.py", line 45, in _set_model
    model.to(globalnames['device'])
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 386, in to
    return self._apply(convert)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 205, in _apply
    self._buffers[key] = fn(buf)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 384, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
configfile:  checkpoint/burgers-noise0.001/options.yaml
configfile:  checkpoint/burgers-noise0.001/options.yaml
configfile:  checkpoint/burgers-noise0.001/options.yaml
repeat batch:16, select device:0
NPSEED: 170, TORCHSEED: 1700
repeat batch:17, select device:1
NPSEED: 180, TORCHSEED: 1800
repeat batch:18, select device:2
NPSEED: 190, TORCHSEED: 1900
repeat batch:19, select device:3
NPSEED: 200, TORCHSEED: 2000
wait
configfile:  checkpoint/burgers-noise0.001/options.yaml
Traceback (most recent call last):
  File "_test_data_gen.py", line 21, in <module>
    globalnames, _, model, data_model, sampling, addnoise = setenv.setenv(options)
  File "/data/users2/sajad/code/PDE-Net/setenv.py", line 68, in setenv
    globalnames, callback, model = _set_model(options)
  File "/data/users2/sajad/code/PDE-Net/setenv.py", line 45, in _set_model
    model.to(globalnames['device'])
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 386, in to
    return self._apply(convert)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 205, in _apply
    self._buffers[key] = fn(buf)
  File "/home/users/mabavisani/anaconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 384, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
configfile:  checkpoint/burgers-noise0.001/options.yaml
configfile:  checkpoint/burgers-noise0.001/options.yaml
configfile:  checkpoint/burgers-noise0.001/options.yaml
